version: "3"
services:
  api:
    build:
      context: .
    environment:
      - SQLALCHEMY_ECHO=False
      - SQLALCHEMY_TRACK_MODIFICATIONS=False
      - SQLALCHEMY_DATABASE_URI=sqlite:///decks.db
    ports:
      - 5000:5000
    volumes:
      - ./app:/src
